language: node_js
node_js:
  - "7"
install:
  - npm i
  - pip install --user hererocks
  - hererocks here --lua 5.3 -r https://github.com/mpeterv/luarocks@upgrade-install
  - export PATH="$PWD/here/bin:$PATH"
  - luarocks install luacheck --upgrade --upgrade-deps
script:
  - luacheck -q ./game/scripts/vscripts
  - npm test
